### ISSUE TITLE
Require paths have priority over metas

### ISSUE THREAD

**Issue by artemking4** [Bilal2453/luvit-sumneko-meta#3]
Using `lit install luvit/luvit` breaks metas

**Comment by artemking4** [comment]
(luvit decided to break requiring on my orangepi for some reason, so i kinda have to do that)

**Comment by Bilal2453** [comment]
That is an interesting issue... I did not expect this to come up. I will see what I can do about it soon.

Note:
For Luvit require to work in Luvi, you just need luvit/require, you can then set that up yourself.  Don't need all of luvit/luvit.

**Comment by artemking4** [comment]
no im actually running it from luvit... the problem is that require is borken and i cba to fix it

**Comment by Bilal2453** [comment]
Could you please contact me on our [Luvit discord server](https://discord.gg/luvit)? If you can.

I suppose what you are going through is one of the side effects of how Luvit's require work.

**Comment by Bilal2453** [comment]
Looking into this again, the more and more I think about it the more it sounds like a user error.  There shall be no reason under which you add Luvit files into the tree if you are using Luvit.  I can't really do much about the extension taking priority for files instead of user downloaded definitions, but this should not be a problem to begin with.

If this is not the case here, please re-open this issue, and post the tree of your project and why it is like this. (There is no reason to do this if you are using the `luvit` binary, you may be running into one of the Luvit's `require` odd behaviors, in which it is a user error.)
